#!/usr/bin/env python3
"""Structural modification of a database framework, under charter section 3.

Section 3 permits modified structures "only if the modified structure is
chemically charge-balanced and its preparation is fully documented and
reproducible from your repository".  The modifications implemented here are
chosen to satisfy that constraint by construction:

  metal <A> -> <B>   isovalent substitution of the framework metal.  Restricted
                     by an explicit whitelist of same-oxidation-state pairs, so
                     the framework's charge balance is unchanged by inspection:
                     no counter-ion is added or removed and no linker is touched.

  H2F <n>            replace n symmetry-distinct hydrogens by fluorine.  H and F
                     are both monovalent and singly bonded, so substituting one
                     for the other leaves the formal charge of every atom
                     unchanged.  Hydrogens are selected deterministically by
                     distance-ordered index so the choice is reproducible.

Geometry is NOT relaxed: the protocol treats frameworks as rigid, and this
toolchain has no relaxation capability. Every modified structure is therefore a
*sensitivity probe on the fixed geometry*, not a proposal for a synthesisable
material, and the final report must say so.

usage: modify.py metal <src.cif> <dst.cif> <from_el> <to_el>
       modify.py H2F   <src.cif> <dst.cif> <count>
"""
import sys, os, math

# Isovalent substitution whitelist.  Each set is a group of elements that occupy
# the same oxidation state in the node chemistry these frameworks are built from,
# so swapping within a set preserves charge balance without touching anything else.
ISOVALENT = [
    {'Mg', 'Ca', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Cd', 'Sr', 'Ba'},   # M(II)
    {'Al', 'Ga', 'In', 'Sc', 'Cr', 'Fe', 'Y', 'La', 'Tb', 'Eu', 'Gd'},    # M(III)
    {'Ti', 'Zr', 'Hf', 'Ce', 'Th', 'U'},                                  # M(IV)
]


def isovalent(a, b):
    return any(a in s and b in s for s in ISOVALENT)


def read_cif(path):
    head, cell, atoms = [], {}, []
    tags = None
    ix = iy = iz = idx_sym = idx_lab = None
    reading = False
    for line in open(path, 'r', errors='replace'):
        s = line.strip()
        low = s.lower()
        if low.startswith('_cell_length_') or low.startswith('_cell_angle_'):
            cell[low.split()[0]] = float(s.split()[1]); continue
        if low == 'loop_':
            tags = []; reading = False; continue
        if tags is not None and s.startswith('_'):
            tags.append(low); continue
        if tags is not None:
            if '_atom_site_fract_x' in tags:
                idx_sym = tags.index('_atom_site_type_symbol') if '_atom_site_type_symbol' in tags else None
                idx_lab = tags.index('_atom_site_label') if '_atom_site_label' in tags else None
                ix = tags.index('_atom_site_fract_x'); iy = tags.index('_atom_site_fract_y')
                iz = tags.index('_atom_site_fract_z'); reading = True
            else:
                reading = False
            tags = None
        if reading and s and not s.startswith('_'):
            t = s.split()
            if len(t) <= max(ix, iy, iz):
                reading = False; continue
            el = t[idx_sym] if idx_sym is not None else ''.join(c for c in t[idx_lab] if c.isalpha())
            atoms.append([el, float(t[ix]), float(t[iy]), float(t[iz])])
    return cell, atoms


def write_cif(path, name, cell, atoms, provenance):
    with open(path, 'w') as f:
        for line in provenance:
            f.write('# %s\n' % line)
        f.write('data_%s\n' % name)
        f.write("_symmetry_space_group_name_H-M   'P 1'\n_symmetry_Int_Tables_number      1\n")
        for k in ('a', 'b', 'c'):
            f.write('_cell_length_%s   %.6f\n' % (k, cell['_cell_length_' + k]))
        for k in ('alpha', 'beta', 'gamma'):
            f.write('_cell_angle_%s   %.6f\n' % (k, cell['_cell_angle_' + k]))
        f.write('loop_\n_atom_site_label\n_atom_site_type_symbol\n'
                '_atom_site_fract_x\n_atom_site_fract_y\n_atom_site_fract_z\n')
        for el, x, y, z in atoms:
            f.write('%-5s %-3s %10.6f %10.6f %10.6f\n' % (el + '_', el, x, y, z))


def main():
    mode, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]
    cell, atoms = read_cif(src)
    name = os.path.basename(dst)[:-4]
    prov = ['generated by bin/modify.py from %s' % os.path.basename(src)]

    if mode == 'metal':
        a, b = sys.argv[4], sys.argv[5]
        if not isovalent(a, b):
            sys.exit('refusing %s->%s: not on the isovalent whitelist, so charge '
                     'balance is not preserved by construction' % (a, b))
        n = sum(1 for at in atoms if at[0] == a)
        if n == 0:
            sys.exit('no %s atoms in %s' % (a, src))
        for at in atoms:
            if at[0] == a:
                at[0] = b
        prov.append('isovalent metal substitution %s -> %s on %d sites' % (a, b, n))
        prov.append('charge balance: %s and %s occupy the same oxidation state in this '
                    'node; no linker, counter-ion or atom count was changed' % (a, b))
        prov.append('geometry NOT relaxed - rigid-framework sensitivity probe')
    elif mode == 'H2F':
        cnt = int(sys.argv[4])
        hs = [i for i, at in enumerate(atoms) if at[0] == 'H']
        if len(hs) < cnt:
            sys.exit('only %d H atoms available, %d requested' % (len(hs), cnt))
        # deterministic, reproducible selection: order by fractional coordinate
        hs.sort(key=lambda i: (atoms[i][1], atoms[i][2], atoms[i][3]))
        for i in hs[:cnt]:
            atoms[i][0] = 'F'
        prov.append('H -> F substitution on %d of %d hydrogens' % (cnt, len(hs)))
        prov.append('charge balance: H and F are both monovalent and singly bonded, so '
                    'every formal charge is unchanged')
        prov.append('sites chosen by sorted fractional coordinate - deterministic and '
                    'reproducible from this repository')
        prov.append('geometry NOT relaxed - rigid-framework sensitivity probe')
    else:
        sys.exit('unknown mode %s' % mode)

    write_cif(dst, name, cell, atoms, prov)
    print('%s: %d atoms -> %s' % (name, len(atoms), dst))


if __name__ == '__main__':
    main()
