#!/usr/bin/env bash
# Write reps/main/collected/COLLECTION.md from what was actually pulled and verified.
# Every number below is read from the collected tree or the seal; none is passed in or asserted.
set -euo pipefail
OUT="$1"; IDS="$2"
cd "$(dirname "$0")/.."
python3 - "$OUT" "$IDS" <<'PY'
import hashlib, json, os, subprocess, sys, datetime
out, ids = sys.argv[1], sys.argv[2].split()
seal = json.load(open("harness/state/sealed_attestation_20260902.json"))
per = seal["per_replicate"]
now_utc = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
rows = []
for r in ids:
    d = os.path.join(out, r)
    def sz(f):
        p = os.path.join(d, f)
        return os.path.getsize(p) if os.path.isfile(p) else None
    commits = sum(1 for _ in open(os.path.join(d, "git-log.txt"))) if os.path.isfile(os.path.join(d, "git-log.txt")) else 0
    audit = sum(1 for _ in open(os.path.join(d, "AUDIT.jsonl"))) if os.path.isfile(os.path.join(d, "AUDIT.jsonl")) else None
    rows.append(dict(rep=r, report=sz("REPORT.md"), log=sz("LOG.md"), commits=commits,
                     audit=audit, cpu=per[r]["final_cpu_h"], sealed=per[r]["record_sha256"][:16],
                     sealcommits=per[r]["commits"]))
tot_cpu = sum(x["cpu"] for x in rows)
tot_b = sum(os.path.getsize(os.path.join(out, r, f)) for r in ids
            for f in os.listdir(os.path.join(out, r)) if os.path.isfile(os.path.join(out, r, f)))

L = []
A = L.append
A("# COLLECTION — main phase, all sixteen replicates")
A("")
A(f"**Pulled and verified {now_utc}.** All sixteen main-phase records are off the cluster and in")
A("`reps/main/collected/`. **Every one reproduces `harness/state/sealed_attestation_20260902.json`")
A("exactly — 16/16, zero drift.**")
A("")
A("Collection is **read-only with respect to the workspaces**. Every remote command in")
A("`harness/pull_collect.sh` is `rsync`-out, `sha256sum` or `git log`. Nothing was written into")
A("`/home1/users/Bei/ws/` by this procedure.")
A("")
A("---")
A("")
A("## 1. Why this ran three days after the campaign closed")
A("")
A("**The harness had no pull.** `transfer.sh` only ever pushes; `collect.sh` reads from a *local*")
A("workspace that the main phase never had, because the sixteen lived on `bnode0` for their entire")
A("campaign. The smoke was pulled by hand on the macOS host that has since been retired, so the")
A("inbound half of collection left with it. This is SI-012's finding — the layer did not travel —")
A("and it is why `screen_launch.sh` refused at its §7.1 barrier twice before tonight.")
A("")
A("`harness/pull_collect.sh` is that missing half. It was written to be the pull and nothing more.")
A("")
A("## 2. Procedure, in the order it ran")
A("")
A("| # | Step | Result |")
A("|---|---|---|")
A(f"| 1 | `rsync` of the eight sealed record files + `AUDIT.jsonl` for each of {len(ids)} workspaces | {tot_b/1e6:.1f} MB |")
A("| 2 | `git log` captured **remotely** — the `.git` trees are not pulled | per-replicate `git-log.txt` |")
A("| 3 | **Independent remote fingerprint**, taken *after* the copy | `BELL_FINGERPRINT.log` |")
A("| 4 | **Verification against the sealed attestation** | **16/16 exact, 0 mismatch** |")
A("| 5 | This file | — |")
A("")
A("**Step 4 is why steps 1–3 can be trusted, and it is stricter than the smoke's.** The smoke")
A("verified its local copy against a fingerprint it had taken itself minutes earlier. This")
A("verification is against a seal taken at **2026-09-01T17:32Z**, hours before the pull existed,")
A("over a manifest fixed before any of these bytes moved. The check recomputes the seal's own")
A("construction — `sha256sum` over the eight files in the seal's order, that output text hashed —")
A("from the **pulled local copies**, and compares. A pull that diverged in one byte of one file")
A("would fail it, and the script halts rather than warns.")
A("")
A("**`BELL_FINGERPRINT.log` is retained for a failure that did not occur:** had a record mismatched,")
A("it distinguishes a bad transfer (local differs from remote) from a workspace that changed after")
A("the seal (local matches remote, and the *seal* disagrees). Those are different findings.")
A("")
A("## 3. What was collected")
A("")
A("| rep | `REPORT.md` | `LOG.md` | commits | `AUDIT.jsonl` | final CPU-h | seal |")
A("|---|---:|---:|---:|---:|---:|---|")
for x in rows:
    a = f"{x['audit']:,}" if x["audit"] is not None else "absent"
    A(f"| {x['rep']} | {x['report']:,} B | {x['log']:,} B | {x['commits']} | {a} | {x['cpu']:,.3f} | `{x['sealed']}…` |")
A(f"| **total** | | | | | **{tot_cpu:,.3f}** | **16/16** |")
A("")
A("**Every replicate filed.** There is no `MISSING_FINAL_REPORT` in this collection: all sixteen")
A("carry a `REPORT.md` under the §7 name, which is also the name the seal hashes and the name")
A("§7.1's gate reads. `FINAL_REPORT.md` is written **as a copy, not a move**, for the smoke's shape;")
A("`REPORT.md` remains binding and is never renamed.")
A("")
A("**Commit counts match the seal for all sixteen** — they are a sealed field, so a rewritten")
A("history would have failed step 4, not merely been noted here.")
A("")
A("## 4. What is NOT in this collection, and why")
A("")
A("**The workspaces themselves were not pulled.** The smoke pulled 3.6 GB of full trees; this pull")
A(f"is {tot_b/1e6:.1f} MB of record. That is a deliberate narrowing to what the seal covers and what")
A("§7.1 gates on, taken because the sixteen carry results, `db/` and `toolchain/` measured in tens")
A("of GB, and because nothing downstream reads them: the screen runs in `/home1/users/Bei/screen/`")
A("and §7.2 forbids it any view of a replicate workspace.")
A("")
A("**Consequences, stated rather than discovered later:**")
A("")
A("- **No local isolation audit.** The smoke's ran only because whole workspaces were on local disk,")
A("  and its first output was six false positives produced by collection itself (absolute symlinks")
A("  resolved against the wrong root). Not run here; not silently reported as clean either.")
A("- **The results are still only on the cluster.** They are outside the seal, outside this")
A("  collection, and outside §7.1's scope. If they are wanted off `bnode0`, that is a separate pull")
A("  against a separate authority, and it should be asked for as one.")
A("")
A("## 5. Contents")
A("")
A("```")
A("collected/")
A("  COLLECTION.md                this file")
A("  BELL_FINGERPRINT.log         independent remote sha256, taken after the copy")
A("  <rep>/")
A("    REPORT.md                  the §7 report — SEALED NAME, binding, never renamed")
A("    FINAL_REPORT.md            copy under the smoke's normalised name")
A("    REPORT_FILENAME_AS_FILED   the name the replicate actually used")
A("    LOG.md STATE.md JOBS.md    the §6 binding record")
A("    ESCALATIONS.md INBOX.md    the §8 channel, both directions")
A("    WORKSPACE.json usage.json  operational parameters and the meters as they stood")
A("    AUDIT.jsonl                where the replicate kept one")
A("    git-log.txt                full commit history, captured remotely")
A("```")
A("")
A(f"**Fleet final: {tot_cpu:,.3f} CPU-h**, the accounting sealed at 17:32Z and reproduced here.")
A("**rep05 remains 0.000 CPU-h against 3 finished jobs** — SI-021's family, carried forward as a")
A("data gap and never as zero compute.")
A("")
A("— Bei (harness)")
open(os.path.join(out, "COLLECTION.md"), "w").write("\n".join(L) + "\n")
print(f"  COLLECTION.md written ({len(L)} lines)")
PY
